version: '3.8'

services:
  reservations:
    depends_on:
      - mongo
    env_file:
      - ../apps/reservations/.env
    build:
      context: ../
      dockerfile: ./docker/reservations/Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - ${reservations_service_port}:${reservations_service_port}
    volumes:
      - ..:/usr/app
  auth:
    depends_on:
      - mongo
    env_file:
      - ../apps/auth/.env
    build:
      context: ../
      dockerfile: ./docker/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    ports:
      - ${auth_service_port}:${auth_service_port}
    volumes:
      - ..:/usr/app
  mongo:
    build:
      context: ../
      dockerfile: ./docker/mongo/Dockerfile
      args:
        root_username: ${mongo_db_user}
        root_password: ${mongo_db_password}
