version: '3.8'

services:
  notifications:
    depends_on:
      - mongo
    env_file:
      - ../apps/notifications/.env
    build:
      context: ../
      dockerfile: ./docker/notifications.Dockerfile
      target: development
    command: yarn start:dev notifications
    ports:
      - ${notifications_service_port}:${notifications_service_port}
    volumes:
      - ..:/usr/app
  payments:
    depends_on:
      - mongo
    env_file:
      - ../apps/payments/.env
    build:
      context: ../
      dockerfile: ./docker/payments.Dockerfile
      target: development
    command: yarn start:dev payments
    ports:
      - ${payments_service_port}:${payments_service_port}
    volumes:
      - ..:/usr/app
  reservations:
    depends_on:
      - mongo
    env_file:
      - ../apps/reservations/.env
    build:
      context: ../
      dockerfile: ./docker/reservations.Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - ${reservations_service_port}:${reservations_service_port}
    volumes:
      - ..:/usr/app
  auth:
    depends_on:
      - mongo
    env_file:
      - ../apps/auth/.env
    build:
      context: ../
      dockerfile: ./docker/auth.Dockerfile
      target: development
    command: yarn start:dev auth
    ports:
      - ${auth_service_port}:${auth_service_port}
    volumes:
      - ..:/usr/app
  mongo:
    build:
      context: ../
      dockerfile: ./docker/mongo.Dockerfile
      args:
        root_username: ${mongo_db_user}
        root_password: ${mongo_db_password}
    ports:
      - ${mongo_service_port}:${mongo_service_port}
